name: deploy gaifaa

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Server
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOME_ADDRESS}}
        username: ${{ secrets.USER }}
        port: 22
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        script: |
          cd Downloads\djangocsv&git pull origin master&iisreset /restart