name: TS

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh key passphrase
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOME_ADDRESS}}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        passphrase: ${{ secrets.PASS }}
        script_stop: true
        script: |
          cd ${{ secrets.REPO_DIR}}
          pwd
          git pull origin master