name: deploy gaifaa

on:
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Server
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOME_ADDRESS}}
        password: ${{ secrets.PASSWORD }}
        port: 22
        username: ${{ secrets.USER }}
        script_stop: true
        script: |
          dir