name: TS

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with: # shimataro/ssh-key-actionに渡すパラメーター
        private-key: ${{ secrets.SSH_KEY }} # 必須
        public-key: ${{ secrets.SSH_KEY_PUB }} # 必須
    - name: SSH  # ステップの名前を指定する
      run: pwd